wjson:
  only:
#    - master
#    - devel
  script:
    - rm -rf faslib | true
    - rm -rf ../faslib | true
    - git clone http://github.lan/cpp/faslib.git
    - cd faslib
    - git checkout devel-0.6
    - mkdir build
    - cd build
    - cmake ..
    - cd ../../
    - ln -s `pwd`/faslib ../faslib
    - ls -l ..
    - mkdir build
    - cd build
    - cmake -I ./faslib -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON ..
    - cmake --build .
    - ctest --output-on-failure
    - cd ..
    - ./.ci/cppcheck.sh
