dist:     trusty
sudo:     required

language: cpp

os:
    - linux

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y valgrind
  - pushd /home/travis/build/mambaru/
  - git clone https://github.com/migashko/faslib.git
  - cd faslib
  - mkdir build
  - cd build 
  - cmake ..
  - popd

compiler:
    - gcc
    - clang
    - g++-5
    - g++-6

env:
    - BUILD_TYPE=Debug BUILD_TESTING=ON PARANOID_WARNING=ON
    - BUILD_TYPE=RelWithDebInfo BUILD_TESTING=ON PARANOID_WARNING=ON
    - BUILD_TYPE=Release BUILD_TESTING=ON PARANOID_WARNING=ON

script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTING=$BUILD_TESTING -DPARANOID_WARNING=$PARANOID_WARNING
    - cmake --build .
    - ctest --output-on-failure

